trigger:
- none

pool:
  sagar-agent

stages:
  - stage: initValidatePlan
    displayName: Terraform init, Terraform validate and Terrafrom plan
    jobs:
      - job: initValidatePlanJob
        displayName: Init, validate and plan
        steps:
        - task: TerraformTask@5
          displayName: Terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            backendServiceArm: 'sagar-svc'
            backendAzureRmStorageAccountName: 'sagarsorage'
            backendAzureRmContainerName: 'terracontainer'
            backendAzureRmKey: 'dev.tfstate'
        - task: TerraformTask@5
          displayName: Terrafrom validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    
        - task: TerraformTask@5
          displayName: Terrafrom plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            environmentServiceNameAzureRM: 'sagar-svc'


  - stage: securityScan
    displayName: security Scan
    jobs:
      - job: tfsectool
        displayName: tfsec tool
        steps:
        - task: tfsec@1
          displayName: TFSEC
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)'

      - job: tflint
        displayName: Tflint tool
        steps:
        - task: CmdLine@2
          continueOnError: true
          displayName: Tflint tool
          inputs:
            script: 'tflint --recursive /f junit > tflint-results.xml'
            workingDirectory: '$(System.DefaultWorkingDirectory)'

        - task: PublishTestResults@2
          displayName: tflint results publish
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'tflint-results.xml'
            testRunTitle: 'tflint results'

  - stage: approvalAndApply
    displayName: Approval And Apply
    jobs:
      - job: Approvals
        pool: server
        displayName: Approval
        steps:
        - task: ManualValidation@1
          displayName: Manual Approver
          inputs:
            notifyUsers: 'sagargujja.devops@gmail.com'
            approvers: 'sagargujja.devops@gmail.com'

      - job: Apply
        dependsOn: Approvals
        displayName: Terraform Apply
        steps:
        - task: TerraformTask@5
          displayName: Terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            backendServiceArm: 'sagar-svc'
            backendAzureRmStorageAccountName: 'sagarsorage'
            backendAzureRmContainerName: 'terracontainer'
            backendAzureRmKey: 'dev.tfstate'
        
        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            environmentServiceNameAzureRM: 'sagar-svc'
